# vim: set ft=ansible
# site.yml
---

- hosts: rhel_repo
  become: true
  vars_files:
    - "./vars/main.yml"
  vars:
    sudo_defaults:
      - defaults: '!requiretty'
  tasks:
    - include: rhel_register.yml
      when: subscribe_rhn|bool == True
      tags:
        - rhel_register
    - include: prepare_system.yml
      tags:
        - prepare_system
    - include: create_mirror.yml
      tags:
        - create_mirror
